### ISSUE TITLE
Provide option to configure deserialization

### ISSUE THREAD

**Issue by danfinlay** [ivanseidel/geddy-rest#1]
Hey Ivan!

Finally got around to trying out your module in a weekend project, and I was using it with Ember.js, and it actually serializes data differently than `geddy-rest` assumes.

This would be easily solved if there were an option key like `optsFromParams`, which would allow users to provide their own options-extraction method.  For ember, I would implement the option like this:

``` javascript
  var modelKey = toCamelCase( geddy.model.Post.modelName );

  geddyRest.RESTify(this, geddy.model.Post, {
    optsFromParams: function (params){
      return params[ modelKey ];
    }
  });
```

I was about to add this myself, but your `_smartDefaults` operation gave me a bit of pause, and I'm not sure where options are being stored anymore, or if they even could be made accessible to the controllers without reorganizing those modules so they support more options.

Do you see an easier approach to this?  My approach was going to be pretty labor intensive, I'm almost inclined to make an ember-centric fork of this in the short term.

**Comment by ivanseidel** [comment]
Hi @flyswatter !

Glad you tested it =)

Try something like this (I don't have a Geddy setup here, so you might try it easier):

```
this.before(function (){
    this.params = this.params.MyEmberKey;
}, {only: ['find', 'create']});
```

If that doesn't fits your case, I guess a smart way to "get" parameters would be nice to implement in the library. `_smartDefaults` is just a way to make sure all keys (create/update/destroy/find) are objects or false. And that inside them, if implemented, they have defaults value. So that:
We don't have incomplete setup objects for each of the four REST types (create/update..)

Did it help?

**Comment by danfinlay** [comment]
Nice, that worked great!

I can't believe I'd never used the .before function before, I bet there are a ton of parts of this framework I just never used, lol.  Thanks!

**Comment by ivanseidel** [comment]
haha
You are welcome ;)

One of the reasons I changed to Geddy, was `THE_MOTHERFUCKING_LOT_OF_CALLBACKS_THAT_ALLOWS_YOU_TO_INJECT_STUFF_ANYWHERE<EVEN_HERE>_LOL`

Did it fully worked?

**Comment by danfinlay** [comment]
I actually need to also serialize responses differently, but now I'm looking into a .after solution..

**Comment by ivanseidel** [comment]
You got the spirit ;)
